---
title: "Graph Visualization"
author: "Dhaval Mandalia"
date: "January 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup Google Chart

```{r Graph_Visualization, results='asis',cache=TRUE}
suppressPackageStartupMessages(library(googleVis))
head(Fruits)
M <- gvisMotionChart(Fruits,"Fruit","Year",options=list(width=600,height=400))
plot(M)
#print(M,"chart")
```
## Plot the map
```{r dependson="Graph_Visualization",results='asis',cache=TRUE}
G <- gvisGeoChart(Exports,locationvar = "Country",colorvar = "Profit",options=list(width=600,height=400))
plot(G)
#print(G,"chart")
```

## Plot the region

```{r dependson="Graph_Visualization",results='asis',cache=TRUE}
G1 <- gvisGeoChart(Exports,locationvar = "Country",colorvar = "Profit",options=list(width=600,height=400,region="150"))
plot(G1)
#print(G,"chart")
```

## Create Line Chart
```{r dependson="Graph_Visualization",results='asis',cache=TRUE}
#df<- data.frame(label=c("US","GB","BR"), val1=c(1,3,4), val2=c(23,12,32))
#Line <- gvisLineChart(df,xvar = "label", yvar = c("val1,val2"),
#                      options = list(title="Worldwide Exports", legend="bottom",
#                                titleTextStyle="{color:'red',fontSize:18}",
#                                vAxis="{gridlines:{color:'red',cound:3}}",
#                                hAxis="{title:'My Label',titleTextStyle:{color:'blue'}}",
#                                series="[{color:'green',targetAxisIndex:0},
#                                          {color:'blue',targetAxisIndex:1}]",
#                                vAxes="[{title:'Value 1 (%)',format:'##,######%'},
#                                          {title:'Value 2 (\U00A3)'}]",
#                                curveType="function", width=500, height=300
#                                ))
```

## Merging Charts
```{r multiplot, dependson="gv",results='asis',cache=TRUE}

G <- gvisGeoChart(Exports,"Country","Profit",options=list(width=200,height=100))
T <- gvisTable(Exports, options=list(width=200,height=270))
M <- gvisMotionChart(Fruits,"Fruit","Year",options=list(width=400,height=370))
GT <- gvisMerge(G,T,horizontal=FALSE)
GTM<-gvisMerge(GT,M,horizontal = TRUE,tableOptions = "bgcolor=\"#CCCCCC\" cellspacing=10")
plot(GTM)
```